using Silvester.Pathfinder.Official.Database.Models;
using System;
using System.Collections.Generic;

namespace Silvester.Pathfinder.Official.Database.Seeding.Seeds
{
    public class DeityCategorySeeder : IEntitySeeder<DeityCategory>
    {
        public IEnumerable<DeityCategory> GetSeedEntities()
        {
            yield return new DeityCategory { Id = Guid.Parse("ab7e9ca8-6361-4309-83c6-6e3b1e5064cc"), Name = "Gods of the Inner Sea", Description = "The 20 primary deities of the Inner Sea region are well known due to either widespread worship or their historical tendency to help or harm the people who live there." };
            yield return new DeityCategory { Id = Guid.Parse("d4f49f9c-0107-478c-9d21-c9c5214e76bb"), Name = "Other Gods", Description = "These deities are not quite as widely worshiped as the 20 primary deities of the Inner Sea region, though they grant their worshippers just as much power and are just as important in their worshippers' lives." };
            yield return new DeityCategory { Id = Guid.Parse("064c64d0-17be-4237-89b0-f04cf6e0fbfe"), Name = "Ancient Osirian Gods", Description = " No official description was provided." };
            yield return new DeityCategory { Id = Guid.Parse("dd52c19b-ce83-4e46-ae17-6560d42c8c1a"), Name = "Archdevils", Description = "Each archdevil holds uncontested rule over one of the first eight realms of Hell." };
            yield return new DeityCategory { Id = Guid.Parse("141f20fa-a6a8-4ac7-88b8-edb2badc5b90"), Name = "Demon Lords", Description = "The Outer Rifts of the Abyss consist of unending layers of evil and depravity, many of which are ruled over by powerful, unique fiends known as demon lords. These demigods have risen above their peers through strength, cunning, or an unmatched capacity for cruelty, overseeing innumerable lesser demons that serve, fear, and revile them. Beneath them, yet more demons clamor to attain their heights of power as nascent demon lords, waiting for the right opportunity to complete their ascension. Fortunately for the mortals of the world, while the ranks of the demon lords are numerous beyond comprehension, only a small subset have so intensely turned their baleful gazes toward Golarion as to have a presence on the planet. These demon lords are served by vile cults that commit atrocities and blasphemies in exchange for power, wealth, and the opportunity to indulge their hearts' darkest desires." };
            yield return new DeityCategory { Id = Guid.Parse("cfa57951-60a1-48eb-9ac7-ff5ac36c8b02"), Name = "Dwarven Gods", Description = "The dwarven gods are one large family, with Torag as its patriarch. He is joined by his brothers Magrim (the Taskmaster) and Angradd (the Forge Fire), his half-sister Dranngvit (the Debt Minder), and his wife Folgrit (the Watchful Mother). His children are Bolka (the Golden Gift), Grundinnar (the Peacemaker), Kols (the Oath-Keeper), and Trudd (the Mighty). Torag's evil former student Droskar (the Dark Smith), though technically part of the dwarven pantheon, is rarely invoked by any save duergars." };
            yield return new DeityCategory { Id = Guid.Parse("e2cdeaf6-9ea1-464c-aa82-045d042da2b5"), Name = "Eldest", Description = "When the gods abandoned the First World—their initial rough draft of creation shaped in distant prehistory— native beings of incredible power stepped in to fill the vacuum. These beings, called the Eldest, hold deific power over the First World but have little of the other gods' aspirations. The Eldest don't concern themselves with expanding their followings or advocating particular ideologies. Many barely acknowledge their worshippers at all, concerning themselves only with their own mysterious motivations and doling out divine power merely because they have much to spare and doing so amuses them." };
            yield return new DeityCategory { Id = Guid.Parse("88b9adbd-19a6-43ae-8086-01688c9c84b2"), Name = "Elemental Lords", Description = "Born amid the primal chaos of the multiverse's earliest days, the eight elemental lords are divine embodiments of the Inner Spheres' raw elemental forces. With two lords of air, two of earth, two of fire, and two of water, half their number represent the aspects of each element that mortals consider benevolent, while the others represent the malicious and destructive aspects of those same elements. When the Material Plane was born, the benevolent elemental lords seeded it with all the potential of their elements, creating planets, stars, oceans, and life. Yet as mortality evolved, it began harnessing the elements for malevolent purposes, causing anguished dissent between the benevolent elemental lords and emboldening their evil counterparts. Kelizandri, the fearsome lord of water, forged an alliance with the other evil elemental lords— Ayrzul, Hshurha, and Ymeri—to seal each good elemental lord in a prison penetrable only by combining the other three elemental powers once more; this feat has been achieved only once in the ages since. The four surviving lords have ruled their respective planes mercilessly for time uncounted, free to write the stories of their own creations, invent their own titles of nobility, and claim sole dominion over the elemental planes." };
            yield return new DeityCategory { Id = Guid.Parse("21e59657-5e46-4c14-87ac-a7349f030f19"), Name = "Elven Gods", Description = "The traditional deities of the elven pantheon are Calistria, Desna, Findeladlara (goddess of twilight and traditional art and architecture), Ketephys (god of hunting and the moon), and Yuelral (goddess of gems, craft, and magic). Elves have also adopted Alseta, a minor goddess of doors and transitions, as their patron of teleportation and aiudara (commonly known as elf gates). Most elves value magic, beauty, freedom, and friendship as part of a fulfilling life and tend to worship all of the deities together as exemplars of these values. Alongside fullblooded elves, many half-elves—whether raised by elves or seeking a closer connection to their elven heritage— worship the elven pantheon." };
            yield return new DeityCategory { Id = Guid.Parse("50493d06-f3a6-4247-abb8-58202aa07447"), Name = "Empyreal Lords", Description = "Much as demon lords and archdevils are the preeminent incarnations of malice and sin, on the side of righteousness stand the empyreal lords—exceptional beings that represent the good in the myriad everyday actions of the multiverse. Drawn from the most powerful ranks of the celestial host, the multitudinous empyreal lords include agathions, angels, archons, and azatas alike. Most of these beings gained prominence as immortal champions of virtue, though some are instead mortal paragons who ascended, while others spontaneously formed from exceptional deeds of good that echoed throughout the planes. While all empyreal lords are dedicated to good, their philosophies, interests, and personalities vary, and they don't always agree with one another. Worship of the empyreal lords is not nearly as widespread as that of the major deities, but it is still surprisingly common. Most worship takes place at small shrines, statues, or artifacts (such as the sculpture known as the Mistress of Angels in Magnimar), or simply through the doing of deeds that reflect an empyreal lord's interest or beliefs. Centers of worship like churches or cathedrals are extremely uncommon. Most followers consider worship to be an individual matter, and it is rare to see a follower of any empyreal lord proselytizing. However, adherents sometimes congregate in small groups called mystery cults, and some of these groups maintain small temples. The city of Magnimar is home to several mystery cults, as the Varisian people have long held the empyreal lords in high esteem. It is not uncommon for mystery cultists to worship multiple empyreal lords in various combinations, or even all of them, though most have a favorite patron." };
            yield return new DeityCategory { Id = Guid.Parse("4d699f44-5321-4d9b-ba78-026c638260e9"), Name = "Horsemen", Description = "At the end of the River Styx await the rulers of Abaddon: the Four Horsemen of the Apocalypse and their daemonic brood. Hatred for living things fuels all of daemonkind, who see existence as a great mistake. Though all of the Horsemen began their lives as mortals, they are completely devoted to the eradication of reality itself. Riding atop their dreaded steeds, they strive for true apocalypse. Only when all life has been snuffed out does their mission end, and they can then consign themselves to the waiting oblivion. Only the truly nihilistic worship the Horsemen. Those who seek vengeance on all the world or lust for power are drawn to the Horsemen's easy promises, thinking they will be spared from their masters' cataclysmic mission. They never are. To the Horsemen, their followers are entirely disposable, tools with a purpose until they too are devoured." };
            yield return new DeityCategory { Id = Guid.Parse("45bda584-ba71-45c5-a91d-a3e9e07ee0a3"), Name = "Monitor Demigods", Description = "While fiends exploit mortals' baser natures and celestials encourage their better selves, monitors are concerned more with method than morality, from the rigid law of aeons and inevitables to the pragmatic neutrality of psychopomps, to the unpredictable chaos of proteans. Rather than immersing themselves in issues of philosophy, monitors take a more cosmic approach, battling each other over universal laws, the planes, and reality itself. Mortals worship monitor demigods just as they do empyreal lords and fiendish demigods. Some are drawn to the enigmatic Monad or primordial inevitables out of a desire for control or the reassurance of an orderly universe—often those in governance or academia. Artists and bon vivants who seek the creativity and freedom offered by the paragons of chaos revere protean lords. While many assume worshippers of psychopomp ushers to be morbid, that is rarely the case. Psychopomp worship is also found among those who bring life into the world, such as midwives and farmers, and those who eschew idealism for more practical philosophies." };
            yield return new DeityCategory { Id = Guid.Parse("1a209857-903b-4a88-9c42-bfcaf5f7b053"), Name = "Old Sun Gods", Description = "Although once mostly forgotten, the Old Sun Gods have slowly been brought back to the people of Mzali thanks to Sihar and the Bright Lions." };
            yield return new DeityCategory { Id = Guid.Parse("cb0c42c1-2f21-4c52-b419-09d55a7b8eca"), Name = "Outer Gods and Great Old Ones", Description = "The Outer Gods, along with the Great Old Ones with whom the Outer Gods are sometimes confused, are ancient, inscrutable, cosmic beings. The Great Old Ones are titanic monstrosities imprisoned since time immemorial beneath the sea, deep within the world, or on other planets, but the Outer Gods are even less comprehensible. These unfathomable entities lurk within the Dark Tapestry—the vast void between the stars on the Material Plane—and dwarf other deities just as those deities dwarf ordinary mortals. To worship these gods is to acknowledge a cold truth: the universe has no meaning. All the things mortal civilizations hold dear—virtues, deities, great works— are things those mortals have invented to distract them from their own insignificance. History is a comforting lie told because mortals are afraid of the dark. The universe is immeasurably vast, beyond understanding, and cares nothing for life. Ultimately, every creature is alone, unmourned, and unloved. And because life has no meaning or purpose, self-indulgence and nihilism are the only rational responses." };
            yield return new DeityCategory { Id = Guid.Parse("95ffee72-4042-47a8-8e82-3ff82c51d55c"), Name = "Pantheons", Description = "A pantheon is a group of related gods worshipped either individually or together. Most pantheons are associated with a specific ancestry or geopolitical region, but rarely, a pantheon consists of deities with overlapping areas of concern. Followers work to advance the shared interests of their pantheon, directing prayers to whichever god presides over their current activity or circumstance. At the GM's discretion, champions and clerics can dedicate themselves to a pantheon. In such cases, the characters still worship a specific patron deity among those in the pantheon, but also follow the edicts and anathema of the pantheon as a whole. A character who worships a pantheon this way can gain the domains, alternate domains, and spells from the pantheon instead of those from their patron deity. They must uphold the ideals of both their patron deity and the pantheon, though the patron deity's edicts and anathema take precedence. For example, a worshipper of Iomedae could worship the Godclaw, but they wouldn't take the tyranny domain, as it would be in conflict with Iomedae's edicts. In rare cases, a character can worship a pantheon without following a patron deity. Such cases are unique and subject to GM approval." };
            yield return new DeityCategory { Id = Guid.Parse("cb6ebc9d-9a0e-4d7c-9a7d-d5da7ea043bd"), Name = "Queens of the Night", Description = "The Queens of the Night have won their own measure of power in Hell." };
            yield return new DeityCategory { Id = Guid.Parse("aa2c5a37-9a30-4bdb-904e-ca1de189edbb"), Name = "Sarkorian Gods", Description = "No official description was provided." };
            yield return new DeityCategory { Id = Guid.Parse("60738a86-c7af-4b79-b29c-a0e861a08da4"), Name = "Tian Gods", Description = "No official description was provided." };
            yield return new DeityCategory { Id = Guid.Parse("9071aac4-ebdd-45a5-ba88-e4af3c56d111"), Name = "Vudrani Gods", Description = "No official description was provided." };
        }
    }
}
