using Silvester.Pathfinder.Official.Database.Extensions;
using Silvester.Pathfinder.Official.Database.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Silvester.Pathfinder.Official.Database.Seeding.Seeds
{
    public class HeritageSeeder : IEntitySeed<Heritage>
    {
        public IEnumerable<Heritage> GetSeedEntities()
        {
            //Versatile Heritage
            yield return new Heritage { Id = Guid.Parse("552b3bc3-c40c-42b6-a13b-436ba14e7c1e"), RarityId = Guid.Parse("7eb0082a-50c0-44ef-a990-7aae6cb9cf27"), Name = "Aasimar", Description = "You descend from celestials or were touched by the celestial realms, gaining an air of awe and grace, as well as features distinctive to your celestial forebears. You gain the aasimar trait, in addition to the traits from your ancestry. You also gain low-light vision, or you gain darkvision if your ancestry already has low-light vision. You can choose from aasimar feats and feats from your ancestry whenever you gain an ancestry feat." };
            yield return new Heritage { Id = Guid.Parse("21a9fd8d-16db-43f2-af67-bd5a97b92d8e"), RarityId = Guid.Parse("7eb0082a-50c0-44ef-a990-7aae6cb9cf27"), Name = "Changeling", Description = "Your mother was a hag. Your heterochromatic eyes are the most obvious signifier of this parentage, but you likely also have a slighter build, paler skin, and darker hair than most members of your other parent’s ancestry. You gain the changeling trait. You also gain low-light vision, or you gain darkvision if your ancestry already has low-light vision. You can select from changeling feats and feats from your other parent’s ancestry whenever you gain an ancestry feat." };
            yield return new Heritage { Id = Guid.Parse("36db9153-1a83-46b1-b303-47a5f4665704"), RarityId = Guid.Parse("7eb0082a-50c0-44ef-a990-7aae6cb9cf27"), Name = "Dhampir", Description = "You are the scion of a vampire, half living and half undead, gifted with uncanny charm and grace, a bloodless pallor, and elongated incisors. You gain the dhampir trait, in addition to the traits from your ancestry. You have the negative healing ability, which means you are harmed by positive damage and healed by negative effects as if you were undead. You also gain low-light vision, or you gain darkvision if your ancestry already has low-light vision. You can choose from dhampir feats and feats from your ancestry whenever you gain an ancestry feat." };
            yield return new Heritage { Id = Guid.Parse("d40a90eb-140a-43b1-94f5-fb034f62d977"), RarityId = Guid.Parse("7eb0082a-50c0-44ef-a990-7aae6cb9cf27"), Name = "Duskwalker", Description = "Thanks to an ancient bargain, your soul has been reborn as a duskwalker, a planar scion with a connection to psychopomps and the Boneyard. You gain the duskwalker trait in addition to the traits from your ancestry. You also gain low-light vision, or you gain darkvision if your ancestry already has low-light vision. Neither your body nor your spirit can ever become undead. You can choose from duskwalker feats and feats from your ancestry whenever you gain an ancestry feat." };
            yield return new Heritage { Id = Guid.Parse("7815fbcb-db7c-42fb-90fd-325aaee20d26"), RarityId = Guid.Parse("7eb0082a-50c0-44ef-a990-7aae6cb9cf27"), Name = "Tiefling", Description = "You descend from fiends or bear the mark of the fiendish realms, manifesting as some unusual feature that belies your heritage, such as horns or a tail. You gain the tiefling trait, in addition to the traits from your ancestry. You also gain low-light vision, or you gain darkvision if your ancestry already has low-light vision. You can choose from tiefling feats and feats from your ancestry whenever you gain an ancestry feat." };

            //Dwarven Heritage
            yield return new Heritage { Id = Guid.Parse("4023db86-7064-4ad0-936e-e1f5c95e921b"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Ancient-Blooded Dwarf", Description = "Dwarven heroes of old could shrug off their enemies’ magic, and some of that resistance manifests in you. You gain the Call on Ancient Blood reaction." };
            yield return new Heritage { Id = Guid.Parse("e019e11d-e494-49d6-8861-5c61a4768b6a"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Anvil Dwarf", Description = "You are a descendant of a famed crafter and have your own amazing talent. Other dwarves might consider this a blessing from your ancestors or from the Forgefather himself, depending on where you grew up. You become trained in Crafting (or another skill if you were already trained in Crafting) and gain the Specialty Crafting skill feat, but you can pick two different specialties instead of one." };
            yield return new Heritage { Id = Guid.Parse("967429bb-5245-4a3c-8468-9177f9f1ff77"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Death Warden Dwarf", Description = "Your ancestors have been tomb guardians for generations, and the power they cultivated to ward off necromancy has passed on to you. If you roll a success on a saving throw against a necromancy effect, you get a critical success instead." };
            yield return new Heritage { Id = Guid.Parse("801fba4a-dd78-4f76-beca-ff51faac7b7a"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Elemental Heart Dwarf", Description = "Whether through a connection to Torag’s forge, the azers of the Plane of Fire, or another source, you can exude a burst of energy. Mbe’ke and Taralu dwarves of the Mwangi Expanse believe this heritage is a gift from dragons or elemental spirits. Choose one of the following damage types: acid, cold, electricity, or fire. Once chosen, this can’t be changed. You gain the Energy Emanation activity." };
            yield return new Heritage { Id = Guid.Parse("541986ae-7349-44fd-8004-c2e606e4f140"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Forge Dwarf", Description = "You have a remarkable adaptation to hot environments from ancestors who inhabited blazing deserts or volcanic chambers beneath the earth. This grants you fire resistance equal to half your level (minimum 1), and you treat environmental heat effects as if they were one step less extreme (incredible heat becomes extreme, extreme heat becomes severe, and so on)." };
            yield return new Heritage { Id = Guid.Parse("88f9765e-66ed-4780-bb53-c23c27b4f8ad"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Oathkeeper Dwarf", Description = "Growing up, you never tried to lie to get what you wanted, and even when necessary, lying makes you uncomfortable. The especially faithful might even have thought that you were blessed by the dwarven god of duty, Kols. You gain a +1 circumstance bonus to Perception checks to Sense Motive and to Perception DCs against attempts to Lie to you. Furthermore, you gain a +2 circumstance bonus to Diplomacy checks to convince others you speak the truth when you are telling the truth, and you take a –4 circumstance penalty to Lie and to your Deception DC against Sense Motive." };
            yield return new Heritage { Id = Guid.Parse("b9e766b7-d4e6-4f93-bc21-8020c2cc09bc"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Rock Dwarf", Description = "Your ancestors lived and worked among the great ancient stones of the mountains or the depths of the earth. This makes you solid as a rock when you plant your feet. You gain a +2 circumstance bonus to your Fortitude or Reflex DC against attempts to Shove or Trip you. This bonus also applies to saving throws against spells or effects that attempt to knock you prone. In addition, if any effect would force you to move 10 feet or more, you are moved only half the distance." };
            yield return new Heritage { Id = Guid.Parse("635245e9-3230-4dab-8b0b-fac29a761c37"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Strong-Blooded Dwarf", Description = "Your blood runs hearty and strong, and you can shake off toxins. You gain poison resistance equal to half your level (minimum 1), and each of your successful saving throws against a poison affliction reduces its stage by 2, or by 1 for a virulent poison. Each critical success against an ongoing poison reduces its stage by 3, or by 2 for a virulent poison." };

            //Elven Heritage
            yield return new Heritage { Id = Guid.Parse("c7209f66-ad64-4356-bf03-aeb4e94bbd6f"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Ancient Elf", Description = "In your long life, you’ve dabbled in many paths and many styles. Choose a class other than your own. You gain the multiclass dedication feat for that class, even though you don’t meet its level prerequisite. You must still meet its other prerequisites to gain the feat." };
            yield return new Heritage { Id = Guid.Parse("62d5db67-945b-4cea-971f-9a2fa5038f2d"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Arctic Elf", Description = "You dwell deep in the frozen north and have gained incredible resilience against cold environments, granting you cold resistance equal to half your level (minimum 1). You treat environmental cold effects as if they were one step less extreme (incredible cold becomes extreme, extreme cold becomes severe, and so on)." };
            yield return new Heritage { Id = Guid.Parse("3623e7a3-e6e0-49d6-bddf-86374cd4e5d3"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Cavern Elf", Description = "You were born or spent many years in underground tunnels or caverns where light is scarce. You gain darkvision." };
            yield return new Heritage { Id = Guid.Parse("4b699d38-c3fc-487c-a55b-f8d561897305"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Desert Elf", Description = "You live under the desert’s blazing heat, gaining incredible resilience to warm environments. You gain fire resistance equal to half your level (minimum 1), and environmental heat effects are one step less extreme for you (incredible heat becomes extreme, extreme heat becomes severe, and so on)." };
            yield return new Heritage { Id = Guid.Parse("f95169fa-400b-446e-8ba2-0dca02ada9bc"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Seer Elf", Description = "You have an inborn ability to detect and understand magical phenomena. You can cast the detect magic cantrip as an arcane innate spell at will. A cantrip is heightened to a spell level equal to half your level rounded up. In addition, you gain a + 1 circumstance bonus to checks to Identify Magic and to Decipher Writing of a magical nature.These skill actions typically use the Arcana, Nature, Occultism, or Religion skill." };
            yield return new Heritage { Id = Guid.Parse("3cd57ab7-c57a-4287-82ce-e1473f75af48"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Whisper Elf", Description = "You're adapted to life in the forest or the deep jungle, and you know how to climb trees and use foliage to your advantage. When Climbing trees, vines, and other foliage, you move at half your Speed on a success and at full Speed on a critical success (and you move at full Speed on a success if you have Quick Climb). This doesn't affect you if you're using a climb Speed. You can always use the Take Cover action when you are within forest terrain to gain cover, even if you're not next to an obstacle you can Take Cover behind." };

            //Gnome Heritage
            yield return new Heritage { Id = Guid.Parse("37a897ea-ac8a-407c-bf26-8443b948c8b3"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Chameleon Gnome", Description = "The color of your hair and skin is mutable, possibly due to latent magic. You can slowly change the vibrancy and the exact color, and the coloration can be different across your body, allowing you to create patterns or other colorful designs. It takes a single action for minor localized shifts and up to an hour for dramatic shifts throughout your body. While you're asleep, the colors shift on their own in tune with your dreams, giving you an unusual coloration each morning. When you're in an area where your coloration is roughly similar to the environment (for instance, forest green in a forest), you can use the single action to make minor localized shifts designed to help you blend into your surroundings. This grants you a +2 circumstance bonus to Stealth checks until your surroundings shift in coloration or pattern." };
            yield return new Heritage { Id = Guid.Parse("6820eb19-bb58-4d56-9fdf-ce57f72b75d6"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Fey-Touched Gnome", Description = "The blood of the fey is so strong within you that you're truly one of them. You gain the fey trait, in addition to the gnome and humanoid traits. Choose one cantrip from the primal spell list. You can cast this spell as a primal innate spell at will. A cantrip is heightened to a spell level equal to half your level rounded up. You can change this cantrip to a different one from the same list once per day by meditating to realign yourself with the First World; this is a 10-minute activity that has the concentrate trait." };
            yield return new Heritage { Id = Guid.Parse("d4c74254-f221-41a2-b2b9-2d8ad741cbc0"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Sensate Gnome", Description = "You see all colors as brighter, hear all sounds as richer, and especially smell all scents with incredible detail. You gain a special sense: imprecise scent with a range of 30 feet. This means you can use your sense of smell to determine the exact location of a creature. The GM will usually double the range if you're downwind from the creature or halve the range if you're upwind. In addition, you gain a + 2 circumstance bonus to Perception checks whenever you're trying to locate an undetected creature that is within the range of your scent." };
            yield return new Heritage { Id = Guid.Parse("1109b6f8-33b0-4868-92f1-49e1ab8135d3"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Umbral Gnome", Description = "Whether from a connection to dark or shadowy fey, from the underground deep gnomes also known as svirfneblin, or another source, you can see in complete darkness. You gain darkvision." };
            yield return new Heritage { Id = Guid.Parse("0bde2b22-b4ee-484d-9052-6c4b47488624"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Vivacious Gnome", Description = "You have an incredibly strong connection to the positive energy that flows through the First World, making it harder to attack your life force with negative energy. You gain negative resistance equal to half your level (minimum 1). When you have the doomed condition, the condition affects you as if its value was 1 lower than it actually is (doomed 1 has no effect, doomed 2 causes you to die at dying 3, and so on)." };
            yield return new Heritage { Id = Guid.Parse("f574f17b-2c71-4a9e-adba-a91a5f5f6e22"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Wellspring Gnome", Description = "Some other source of magic has a greater hold on you than the primal magic of your fey lineage does. This connection might come from an occult plane or an ancient occult song; a deity, celestial, or fiend; magical effluent left behind by a mage war; or ancient rune magic. Choose arcane, divine, or occult.You gain one cantrip from that magical tradition's spell list. You can cast this spell as an innate spell at will, as a spell of your chosen tradition. A cantrip is heightened to a spell level equal to half your level rounded up. Whenever you gain a primal innate spell from a gnome ancestry feat, change its tradition from primal to your chosen tradition." };

            //Goblin Heritage
            yield return new Heritage { Id = Guid.Parse("b5615a58-0fc5-4b2d-87b7-b3f2e74e3a10"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Charhide Goblin", Description = "Your ancestors have always had a connection to fire and a thicker skin, which allows you to resist burning. You gain fire resistance equal to half your level (minimum 1). You can also recover from being on fire more easily. Your flat check to remove persistent fire damage is DC 10 instead of DC 15, which is reduced to DC 5 if another creature uses a particularly appropriate action to help." };
            yield return new Heritage { Id = Guid.Parse("d1269abf-7396-4b72-8130-9a74f3253bfb"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Irongut Goblin", Description = "You can subsist on food that most folks would consider spoiled. You can keep yourself fed with poor meals in a settlement as long as garbage is readily available, without using the Subsist downtime activity. You can eat and drink things when you are sickened. You gain a + 2 circumstance bonus to saving throws against afflictions, against gaining the sickened condition, and to remove the sickened condition.When you roll a success on a Fortitude save affected by this bonus, you get a critical success instead.All these benefits apply only when the affliction or condition resulted from something you ingested." };
            yield return new Heritage { Id = Guid.Parse("14a46d8b-148c-4671-90ec-622b746f75e0"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Razortooth Goblin", Description = "Your family's teeth are formidable weapons. You gain a jaws unarmed attack that deals 1d6 piercing damage. Your jaws are in the brawling group and have the finesse and unarmed traits." };
            yield return new Heritage { Id = Guid.Parse("e6c22bc6-bb97-480b-85c3-6d1b2dd3980a"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Snow Goblin", Description = "You are acclimated to living in frigid lands and have skin ranging from sky blue to navy in color, as well as blue fur. You gain cold resistance equal to half your level (minimum 1). You treat environmental cold effects as if they were one step less extreme (incredible cold becomes extreme, extreme cold becomes severe, and so on)." };
            yield return new Heritage { Id = Guid.Parse("4a851a94-b9dd-4afe-b74e-4c3ef1407d9f"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Tailed Goblin", Description = "You have a powerful tail, likely because you descend from a community of monkey goblins. You gain a +2 circumstance bonus to Athletics checks to Climb, you gain Combat Climber as a bonus feat, and you reduce the number of free hands required to Climb or Trip by one." };
            yield return new Heritage { Id = Guid.Parse("35e10760-e9f1-4570-89f6-7fd2c3ecee42"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Treedweller Goblin", Description = "You have adapted particularly well to living in forested environments. As long as you are in a forest or jungle, you gain a +2 circumstance bonus to Stealth checks to Hide and Sneak, Survival checks to Subsist, and your Survival DC to Cover Tracks." };
            yield return new Heritage { Id = Guid.Parse("634935e2-14bd-4de5-b1d9-fcff13093d94"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Unbreakable Goblin", Description = "You’re able to bounce back from injuries easily due to an exceptionally thick skull, cartilaginous bones, or some other mixed blessing. You gain 10 Hit Points from your ancestry instead of 6. When you fall, reduce the falling damage you take as though you had fallen half the distance." };

            //Halfling Heritage
            yield return new Heritage { Id = Guid.Parse("4ce3660b-c78a-4eb5-b487-e234132f4f34"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Gutsy Halfling", Description = "Your family line is known for keeping a level head and staving off fear when the chips were down, making them wise leaders and sometimes even heroes. When you roll a success on a saving throw against an emotion effect, you get a critical success instead." };
            yield return new Heritage { Id = Guid.Parse("2edffa58-9514-4e51-82f8-e1b08e427aeb"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Hillock Halfling", Description = "Accustomed to a calm life in the hills, your people find rest and relaxation especially replenishing, particularly when indulging in creature comforts. When you regain Hit Points overnight, add your level to the Hit Points regained. When anyone uses the Medicine skill to Treat your Wounds, you can eat a snack to add your level to the Hit Points you regain from their treatment." };
            yield return new Heritage { Id = Guid.Parse("c2c39377-feae-4142-a4c9-6d0e458d355c"), RarityId = Guid.Parse("7eb0082a-50c0-44ef-a990-7aae6cb9cf27"), Name = "Jinxed Halfling", Description = "You were born with a strange blessing: bereft of the typical halfling luck, you can instead manipulate the fortunes of others. You can never take the Halfling Luck feat, and you gain the Jinx action." };
            yield return new Heritage { Id = Guid.Parse("dce19cbd-7be3-4fd6-939b-48712d5f6daa"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Nomadic Halfling", Description = "Your ancestors have traveled from place to place for generations, never content to settle down. You gain two additional languages of your choice, chosen from among the common and uncommon languages available to you, and every time you take the Multilingual feat, you gain another new language." };
            yield return new Heritage { Id = Guid.Parse("cbaec7eb-4492-42a3-83ac-1e82a5658fb8"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Observant Halfling", Description = "Your finely honed senses quickly clue you in to danger or trickery. You gain a +1 circumstance bonus to your Perception DC, though not to your Perception checks." };
            yield return new Heritage { Id = Guid.Parse("a8c3e70e-6eb6-4a5e-85cd-755eccc7677e"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Twilight Halfling", Description = "Your ancestors performed many secret acts under the concealing cover of dusk, whether for good or ill, and over time they developed the ability to see in twilight beyond even the usual keen sight of halflings. You gain low-light vision." };
            yield return new Heritage { Id = Guid.Parse("0b36fe08-7970-45a3-a816-05d187ae1709"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Wildwood Halfling", Description = "You hail from deep in a jungle or forest, and you’ve learned how to use your small size to wriggle through undergrowth, vines, and other obstacles. You ignore difficult terrain from trees, foliage, and undergrowth." };

            //Human Heritage
            yield return new Heritage { Id = Guid.Parse("fdf36b32-00b2-457f-9aca-aa9378c0f92e"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Skilled Heritage", Description = "Your ingenuity allows you to train in a wide variety of skills. You become trained in one skill of your choice. At 5th level, you become an expert in the chosen skill." };
            yield return new Heritage { Id = Guid.Parse("03cbc90d-fbf1-488b-ab42-47a80884c75a"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Versatile Heritage", Description = "Humanity's versatility and ambition have fueled its ascendance to be the most common ancestry in most nations throughout the world. Select a general feat of your choice for which you meet the prerequisites (as with your ancestry feat, you can select this general feat at any point during character creation)." };
            yield return new Heritage { Id = Guid.Parse("03d1ff17-a448-47c9-b71f-5973a66e2563"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Wintertouched Human", Description = "The power of winter flows through you. This heritage is most common among the Jadwiga of Irrisen, due to their descent from Baba Yaga, and certain Erutaki touched by the spirits. You gain cold resistance equal to half your level (minimum 1), and you treat environmental cold effects as if they were one step less extreme (incredible cold becomes extreme, extreme cold becomes severe, and so on)." };
            yield return new Heritage { Id = Guid.Parse("a3b12707-a7f5-41f0-9f49-f41d1839d5f7"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Half-Elf", Description = "Either one of your parents was an elf, or one or both were half-elves. You have pointed ears and other telltale signs of elf heritage. You gain the elf trait, the half-elf trait, and low-light vision. In addition, you can select elf, half-elf, and human feats whenever you gain an ancestry feat." };
            yield return new Heritage { Id = Guid.Parse("b54692a4-5791-4971-9590-17889ca0cbaa"), RarityId = Guid.Parse("dff7388d-fd99-4a7d-8d0b-3d9b18dcb807"), Name = "Half-Orc", Description = "One of your parents was an orc, or one or both were half-orcs. You have a green tinge to your skin and other indicators of orc heritage. You gain the orc trait, the half-orc trait, and low-light vision. In addition, you can select orc, half-orc, and human feats whenever you gain an ancestry feat." };
        }
    }

    public class HeritageRaceJoiner : IEntityJoin<Heritage, Race>
    {
        public Race[] Join(Heritage heritage, Race[] races)
        {
            return heritage.Name switch
            {
                "Aasimar" => races,
                "Changeling" => races,
                "Dhampir" => races,
                "Duskwalker" => races,
                "Tiefling" => races,

                "Ancient-Blooded Dwarf" => Filter(races, "Dwarf"),
                "Anvil Dwarf" => Filter(races, "Dwarf"),
                "Death Warden Dwarf" => Filter(races, "Dwarf"),
                "Elemental Heart Dwarf" => Filter(races, "Dwarf"),
                "Forge Dwarf" => Filter(races, "Dwarf"),
                "Oathkeeper Dwarf" => Filter(races, "Dwarf"),
                "Rock Dwarf" => Filter(races, "Dwarf"),
                "Strong-Blooded Dwarf" => Filter(races, "Dwarf"),

                "Ancient Elf" => Filter(races, "Elf"),
                "Arctic Elf" => Filter(races, "Elf"),
                "Cavern Elf" => Filter(races, "Elf"),
                "Desert Elf" => Filter(races, "Elf"),
                "Seer Elf" => Filter(races, "Elf"),
                "Whisper Elf" => Filter(races, "Elf"),

                "Chameleon Gnome" => Filter(races, "Gnome"),
                "Fey-Touched Gnome" => Filter(races, "Gnome"),
                "Sensate Gnome" => Filter(races, "Gnome"),
                "Umbral Gnome" => Filter(races, "Gnome"),
                "Vivacious Gnome" => Filter(races, "Gnome"),
                "Wellspring Gnome" => Filter(races, "Gnome"),

                "Charhide Goblin" => Filter(races, "Goblin"),
                "Irongut Goblin" => Filter(races, "Goblin"),
                "Razortooth Goblin" => Filter(races, "Goblin"),
                "Snow Goblin" => Filter(races, "Goblin"),
                "Tailed Goblin" => Filter(races, "Goblin"),
                "Treedweller Goblin" => Filter(races, "Goblin"),
                "Unbreakable Goblin" => Filter(races, "Goblin"),

                "Gutsy Halfling" => Filter(races, "Halfling"),
                "Hillock Halfling" => Filter(races, "Halfling"),
                "Jinxed Halfling" => Filter(races, "Halfling"),
                "Nomadic Halfling" => Filter(races, "Halfling"),
                "Observant Halfling" => Filter(races, "Halfling"),
                "Twilight Halfling" => Filter(races, "Halfling"),
                "Wildwood Halfling" => Filter(races, "Halfling"),

                "Skilled Heritage" => Filter(races, "Human"),
                "Versatile Heritage" => Filter(races, "Human"),
                "Wintertouched Human" => Filter(races, "Human"),
                "Half-Elf" => Filter(races, "Human", "Elf"),
                "Half-Orc" => Filter(races, "Human", "Orc"),
                _ => Array.Empty<Race>()
            };
        }

        private static Race[] Filter(Race[] races, params string[] raceNames)
        {
            Race[] matches = races
                .Where(domain => raceNames.Contains(domain.Name))
                .ToArray();

            return matches.Length == raceNames.Length
                ? matches
                : throw new InvalidOperationException($"Not all race names could be found: {string.Join(", ", matches.Select(e => e.Name).GetMissing(raceNames))}.");
        }
    }
}
