using Silvester.Pathfinder.Official.Database.Models;
using System;
using System.Collections.Generic;

namespace Silvester.Pathfinder.Official.Database.Seeding.Seeds
{
    public class PlaneCategorySeeder : IEntitySeed<PlaneCategory>
    {
        public IEnumerable<PlaneCategory> GetSeedEntities()
        {
            yield return new PlaneCategory { Id = Guid.Parse("906654b0-cf06-4b89-981b-07b50afa956d"), Name = "Dimension", Description = "Existing in the metaphorical space between the Transitive Planes and smaller, finite demiplanes, dimensions are a category unto themselves, defying the neat categorization of planar scholars and adventurers. Seemingly infinite in scale, not necessarily spatial in the same way as a plane, and overlaying every other plane at once—including one another—dimensions and planes are most significantly differentiated in how each of them breaks the commonly held rules of the other. Although some scholars include other extraplanar realms within the ranks of dimensions, only two such realms are uniformly agreed upon and classified as such. The Dreamlands, also known as the Dimension of Dreams, is readily accessed by mortal dreamers, while the Dimension of Time is notorious for the near impossibility of accessing it as well as the bizarre, often deadly restrictions upon travel to and within its bounds." };
            yield return new PlaneCategory { Id = Guid.Parse("3bbe8661-ea39-4b26-8723-eb04b151062f"), Name = "Inner Sphere Plane", Description = "The planes of the Inner Sphere form the heart of the cosmos. They are the home of mortal life, the focus of divine attention, the source of mortal souls, and the origin point of the great cycle of quintessence that fuels the motions and stability of reality itself. Arranged in a nested series of shells, like layers of an onion, the planes of the Inner Sphere include, from outer to inner: the Elemental Planes of Fire, Earth, Water, and Air; the universe of the Material Plane; and at the very core of this cosmological ensemble, the raw forces of creation and destruction of the Positive and Negative Energy Planes." };
            yield return new PlaneCategory { Id = Guid.Parse("c64c6e93-aa40-4010-8fbc-592c1f0e017a"), Name = "Outer Sphere Plane", Description = "The planes of the Outer Sphere are the manifest realms of alignment: chaos, evil, good, law, neutrality, and their admixtures, populated by celestials, fiends, monitors, and others who promote these moral concepts. These planes are the backdrop upon which the mortal afterlife reaches its apparent conclusion, and the end destination of the River of Souls. The Outer Planes are regions of stability adrift in the raw, chaotic quintessence of the primordial Maelstrom, its tides forever gnawing at their edges even as mortal souls sustain them. The Abyss manifests as cracks in the Outer Sphere’s fabric, while rising from the metropolitan Axis is the Boneyard’s spire, the location where mortal souls are judged and then sent to their final destinations, be they reward, suffering, or oblivion. The Outer Planes are places of majesty, wonder, terror, and danger outstripping anything mortal adventurers might encounter anywhere else." };
            yield return new PlaneCategory { Id = Guid.Parse("a1485da2-c025-45cd-bc59-f08fe12b7d5b"), Name = "Transitive Plane", Description = "At a minimum, each Transitive Plane coexists with one or more other planes, a relationship oversimplified by stating that Transitive Planes are just used to get from one plane to another. The mists of the Ethereal Plane overlap the planes of the Inner Sphere, while the Astral Plane borders every other plane in existence like the backstage of the cosmos. Bright and dark mirrors of the Material Plane, the First World and Shadow Plane overlap the mortal world, albeit often in bizarre ways such that a short distance in one might be a vast gulf in the other. The daring, wise, or desperate can utilize these planes to bypass barriers in the Material Plane or rapidly cross vast distances through much swifter travel." };
        }
    }
}
