using Silvester.Pathfinder.Official.Database.Extensions;
using Silvester.Pathfinder.Official.Database.Models;
using System;
using System.Collections.Generic;
using System.Linq;

using Plane = Silvester.Pathfinder.Official.Database.Models.Plane;

namespace Silvester.Pathfinder.Official.Database.Seeding.Seeds
{
    public class PlaneSeeder : IEntitySeeder<Plane>
    {
        public IEnumerable<Plane> GetSeedEntities()
        {
            //Transitive Planes
            yield return new Plane { Id = Guid.Parse("2e98856d-d10d-46c9-8d7a-fe12e6581733"), CategoryId = Guid.Parse("a1485da2-c025-45cd-bc59-f08fe12b7d5b"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Astral Plane", Description = "The Silver Sea surrounds the planes of the Inner Sphere, separating them from those of the Outer Sphere. The Astral Plane provides the backdrop against which the River of Souls flows from the Material Plane, ushering departed spirits toward final judgment. Far from an empty void, the Astral’s silver substance churns with currents and storms from the metaphysical heat of the Plane of Fire, and where it touches the chaos of the Maelstrom, the resulting eddies interact with the memories of the dead to produce fleeting simulacra and even demiplanes. The River of Souls draws the attention of soul - hunting daemons and opportunistic night hags like sharks drawn to the scent of blood.Led by psychopomps, a cross section of nearly every type of celestial and monitor in existence, along with some fiends, defends the proper flow of souls against such predators.Running opposite the River of Souls is the flow of raw, unaligned quintessence spun off from the so-called Antipode, channeled by aeons back toward the Positive Energy Plane. Travelers within the Astral find the plane untouched by the passage of time a property exploited by many mortals fearing old age. Time however, is not easily escaped, and upon exiting the Astral Plane, a creature finds this debt catching up to them, potentially aging to dust in moments." };
            yield return new Plane { Id = Guid.Parse("4d67dae9-fa19-4ce6-be98-e52a7ca93f09"), CategoryId = Guid.Parse("a1485da2-c025-45cd-bc59-f08fe12b7d5b"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Ethereal Plane", Description = "The Ethereal Plane is a vast, misty realm overlapping each of the Inner Planes. Formed by the interacting tidal forces of creation and destruction from the Positive and Negative Energy Planes, this plane swirls with currents and eddies of fog, lit only by erratic pulses of soft green luminescence and dimly visible light of those planes it overlays, visible but ever intangible. While mortals most often use the Ethereal as a means of transit, moving by force of will in the absence of gravity to bypass barriers on their own plane, the Ethereal hosts dangers and wonders, things lost or abandoned in the mists, and things spun from local eddies in the ethereal protomatter. Predatory monsters, ether spiders, night hags and their goddess Alazhra, and all manner of incorporeal undead roam the Space Between Spaces. While travelers can easily become lost in the mists with little to guide them the plane does host some permanent structures drawing adventurers or dissuading them.One such location, the House of the Itinerant Soul, houses wayward or lost souls, offering visitors shelter and a way to avoid turning into undead while avoiding the pull of the River of Souls.The grand cathedral also serves as a focus for mortal planar travelers, given its safety and the presence of friendly spirits willing to serve as guides in the surrounding mists." };
            yield return new Plane { Id = Guid.Parse("e48dae17-e2ad-48fa-8cfb-756dea200ca5"), CategoryId = Guid.Parse("a1485da2-c025-45cd-bc59-f08fe12b7d5b"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "First World", Description = "The First World was a first draft of the Material Plane, crafted by divinities to test their metaphorical crafting materials and palettes of colors before setting it aside to create a second, final version of their work. A realm of extremes—savage, primal, and beautiful—with colors and sensations brighter and more intense than the mundane world created after it, the First World is populated by fey and the divine entities known as the Eldest. Mirroring mercurial fey whimsy, the First World’s laws of nature constantly and unpredictably change. Distance and time are wildly inconsistent, such that mortal travelers might spend an hour or a day within the First World, only to find a century or only a few seconds passed once they return to their own plane. The First World stands outside the cycle of souls, something the fey call the Great Abandonment, save for rare worshippers of the Eldest whose souls incarnate here as fey.However, the plane’s proximity to the Positive Energy Plane provides an environment bursting with all manner of strange life and a general absence of true death for its native fey unless they leave—as did gnomes.Natural gates in wild places of the mortal realm connect to the First World, which fey often use to visit the Material Plane or ensnare mortals for their own capricious desires." };
            yield return new Plane { Id = Guid.Parse("3e4b22a2-a4bd-42cc-b27f-a381758a4c11"), CategoryId = Guid.Parse("a1485da2-c025-45cd-bc59-f08fe12b7d5b"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Shadow Plane", Description = "A murky, distorted, and imperfect mirror of the Material Plane, the Shadow Plane overlaps the Material Plane and serves as a buffer or conduit between it and the Negative Energy Plane. The Shadow Plane exists in a state of perpetually dim half-light, the landscape containing similar features to the overlapping Material Plane, but in warped or twisted fashions. Cities on the Material Plane might exist on the Shadow Plane, sometimes in ruins and sometimes as terrible, frightening replicas. The darkness also holds points of beauty and relative safety, such as the great city of Shadow Absalom. The bleak doppelganger of Golarion’s own Absalom hosts cross-planar trade facilitated by a permanent, one-way portal out of the gloom. The Shadow Plane is populated by dark, altered versions of creatures from the Material Plane, many of them immigrants that have adapted to the shadow after being trapped in the realm for generations.The shadow natives known as kayals—also known as fetchlings—were originally humans before thousands of years of exposure to the Shadow Plane and breeding with strange beings forever altered them.Velstracs, who long ago fled from Hell, have since adopted the Shadow Plane as their home, spreading their horrific message of perfection through mutilation in service to their victim and patron, the god Zon - Kuthon.In contrast, d’ziriaks originated within the Shadow Plane itself, as have the fearsome umbral dragons ruling self - crafted fiefdoms within the shadows.Greatest of these is Argrinyxia, who rules over Shadow Absalom." };

            //Dimensions
            yield return new Plane { Id = Guid.Parse("8e6d1e80-b710-4468-89d5-a97d4178fd14"), CategoryId = Guid.Parse("906654b0-cf06-4b89-981b-07b50afa956d"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Dimension of Time", Description = "Among the most obscure planes of existence, the Dimension of Time is virtually impossible to access by conventional methods of planar travel. Instead, travelers much perform complex and difficult rituals described within the pages of such monstrously rare tomes as the Necronomicon and the Book of Serpents, Ash, and Acorns: Shadows of What Was and Will Be. Compounding the plane’s obscurity, each traveler’s experience seems to be unique, and most who attempt the journey never return. Every manner of magic that interacts with the plane invariably draws the attention of creatures such as the hounds of Tindalos. The proper flow and continuity of time seems to self-correct for any attempted meddling, often with violence. Those few who have gained entry and returned describe the plane as a swirling storm of blurred images, the composite of millions of interwoven timelines around their own, with a single doorway allowing access to one’s own past.Travelers appear as transparent images of themselves, but the plane seems averse to any attempt to alter the past, no matter the means or the intention.Such attempts often end in the offending individual erased from existence or trapped within closed time loops to limit the damage they inflict upon the overall flow of time. Supposedly, like an eye in a storm, at the dimension’s heart is the legendary realm of Stethelos and its terrible occupant Tawil at’Umr.Tales of this realm speak only of a great city, a vast green meadow, and the rushing sound of an ocean emptying over an immense and terrible waterfall." };
            yield return new Plane { Id = Guid.Parse("08350a3e-6f60-4b40-b5f0-8ec05e70204e"), CategoryId = Guid.Parse("906654b0-cf06-4b89-981b-07b50afa956d"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Dreamlands", Description = "Created and sustained by the collective dreams of sleeping mortals, the Dreamlands (also called the Dimension of Dreams) overlays the Ethereal Plane. When a creature dreams, regardless of the location of their physical body, they interact directly with the Dreamlands. Sleeping creatures cast themselves into the plane in idealized avatars known as lucid bodies, and their dreamscapes are immune to outside entry by standard magic such as plane shift, requiring obscure, more specialized spells to access. The dreamers of each mortal world generate a cluster of dreamscapes, like drifting bubbles atop a deeper ocean of permanent dreams formed from the collective mass of slumbering desires, dreams of especially powerful dreamers, and the dreams of ancient, obscure entities—including the gods of the Elder Mythos. While most dreamscapes are safe, travelers in the deep, permanent Dreamlands face living, animate dreams and the predation of night hags from the Ethereal Plane, as well as stranger beings spawned within the core itself. Some scholars postulate a distinct region within the dimension for nightmares, much as the more stable inner portions of the dimension exist separately from the transient, ever - forming and evaporating mortal dreamscapes at its edges.Others conflate this nightmare region with the demiplane of Leng, while still others dismiss this notion but speculate that Leng is somehow accessible to dreamers who intentionally seek it out." };

            //Inner Sphere Planes
            yield return new Plane { Id = Guid.Parse("af0a9351-d4e7-492d-93c4-2b7ef86cfa85"), CategoryId = Guid.Parse("3bbe8661-ea39-4b26-8723-eb04b151062f"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Material Plane", Description = "The Material Plane is the prosaic universe and the home of mortal life. Innumerable galaxies play host to countless stars and their planets, each housing unique settings for any campaign, with Golarion as the classic example. Other worlds of note like Castrovel, Akiton, and Eox exist within Golarion’s own solar system, and then beyond this, orbiting other distant stars or in other galaxies still, worlds such as Androffa, Carcosa, and even Earth swirl within the Material Plane’s vast and silent void. Yet for all the profound wonder and diversity of life that the Material Plane houses, in the dark places between the stars, known as the Dark Tapestry, lurk the inimical gods known as the Outer Gods and Great Old Ones, the sinister collective known as the Dominion of the Black. The Material Plane serves as the destination for pre - incarnate souls, each mortal life born, living, and dying before sending its spirit toward the planes of the Outer Sphere for judgment.The Material Plane is likewise the focus of the gods, each of whom is invested in fostering their own particular portfolio among mortal worshippers and the material world at large." };
            yield return new Plane { Id = Guid.Parse("1a0e31c5-8271-458c-a941-d1a9a5a60d51"), CategoryId = Guid.Parse("3bbe8661-ea39-4b26-8723-eb04b151062f"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Negative Energy Plane", Description = "The vast void of the Negative Energy Plane is a merciless, lightless expanse of manifest destruction and nothingness. Sapping and consuming the life force of any living creature exposed to its energies, it corrodes and disintegrates material objects to rubble, then dust, and then nothing at all. Yet the Void contains its own form of anti-life. At their densest concentration, the plane’s energies aggregate into bizarre, black crystalline snowflake structures, and these irregularities spontaneously generate the plane’s resident sceaduinars. Dwelling in beautiful, deadly cities drifting in the vacuous darkness, these so-called void raptors are incapable of true creation and blame this flaw on some ancient betrayal by their rivals on the Positive Energy Plane. Sceaduinars react violently not only toward creatures sustained by positive energy, but also toward undead, whom they view as unnatural parasites unworthy of their plane’s energies. The black depths also swarm with undead, creatures doomed to a mockery of life by the interaction of their souls with the plane’s entropic energy.Yet for all the horrors posed by the plane’s environment, inhabitants, and its undead victims, its depths nevertheless hide rare refuges for planar travelers. Malikar’s Keep offers shelter, for a price, to those willing to bargain with its titular lich master, while elsewhere the depths hide entire lost worlds such as Fallen Duromak, and deadly mysteries like the planet-sized, undead - entrapping glass sphere, Eternity’s Doorstep." };
            yield return new Plane { Id = Guid.Parse("b191ffc0-7a9a-4285-b758-7542bef75a85"), CategoryId = Guid.Parse("3bbe8661-ea39-4b26-8723-eb04b151062f"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Plane of Air", Description = "The Plane of Air, innermost of the Elemental Planes, is a vast realm of wind, storms, and skies. Illuminated by great artificial globes of flame and distant starlight from the material universe, the plane is populated by air elementals, dragons, mephits, and a great empire of djinn. Though mostly clouds and empty skies, the plane is not entirely bereft of solid ground, including rock and ice created by the residents or dragged into their realm from the distant Plane of Earth or neighboring Plane of Water, and bizarre, drifting spheres of brass and iron. While the former are aggressively fought over, most housing the cities of the vast djinn empire, the latter are almost entirely abandoned and shunned by the plane’s inhabitants, who believe them cursed, entrapping forgotten, ancient enemies who once ravaged the plane. The djinn rule from their shining capital city of Armun Kelisk, built atop a series of seven floating islands.Their vast trade network crisscrosses the skies and ventures to other planes, kept aloft by natural and magical flight, including great airships that allow visitors to quickly and safely traverse the skies.The djinn are welcoming and gracious hosts to extraplanar travelers and adventurers, a perspective not shared by Hshurha the Duchess of All Winds, the evil elemental lord of air." };
            yield return new Plane { Id = Guid.Parse("71064085-85ef-4986-b34c-c270b398749a"), CategoryId = Guid.Parse("3bbe8661-ea39-4b26-8723-eb04b151062f"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Plane of Earth", Description = "A great and rocky shell situated between the Plane of Fire and Plane of Water, the Eternal Delve hosts a unique and varied ecology of creatures at home in its rocky depths. Far from an endless, solid expanse, the Plane of Earth is riddled with great caverns and cave systems, excavated artificial vaults, vast crystalline geodes, and underground oceans and springs of magma where it borders its neighboring planes. Housing untold riches in gemstones and veins of precious metals, the Plane of Earth is an attractive setting for planar travelers seeking wealth and willing to risk danger and the wrath of elementals, shaitans, and other inhabitants who resent the plunder of their home. While elementals have little organized society, the shaitan genies’ Peerless Empire rules much of the plane from its capital, the Opaline Vault—a rainbow - lit city within a 30 - mile - wide geode cavern.The shaitans have long been at war with the efreet in the neighboring Plane of Fire, and while the earth genies are less prone to slavery than their rivals, the shaitans brook little dissent, and their rule can be harsh.They are downright welcoming, however, compared to Ayrzul the Fossilized King, the evil elemental lord of earth who rules a great expanse of rock from his radiation-poisoned domain, the Blistering Labyrinth." };
            yield return new Plane { Id = Guid.Parse("d1670c72-3c58-4e8a-8c36-6dd1d944383d"), CategoryId = Guid.Parse("3bbe8661-ea39-4b26-8723-eb04b151062f"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Plane of Fire", Description = "Like a great, gleaming ball of flame situated at the heart of the Astral Plane, the Plane of Fire is the outermost plane of the Inner Sphere. A perpetual ocean of fire with skies of smoke, storms of raining cinders, and lakes and rivers of magma flowing along its border with the Elemental Plane of Earth, the plane is incredibly hostile to those unprepared for its natural hazards. Yet it houses one of the most well-known and traversed cities in all the planes: the City of Brass, capital of the Dominion of Flame. Floating above a sea of fire upon a great hemisphere of magical brass, the City of Brass is a monument both to efreet cosmopolitan grandeur and tyranny, the latter embodied by the grand sultana of the efreet. Outside of the mercantile districts and the palaces and temples of the fire genies, the city houses a vast enslaved underclass of salamanders and others, including creatures from other planes. The efreeti domain is not absolute, and elsewhere in the plane are nations of fire mephits and the remains of an ancient azer empire.While they don’t form any cohesive, organized nations, the plane’s fire elementals are ruled over by the plane’s most powerful entity, Ymeri the Queen of the Inferno, the evil elemental lord of fire whose reign has gone unquestioned since the imprisonment of her good - aligned rival Atreia eons ago." };
            yield return new Plane { Id = Guid.Parse("f4048c73-6fb0-496c-9e7b-dff087bea6ef"), CategoryId = Guid.Parse("3bbe8661-ea39-4b26-8723-eb04b151062f"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Plane of Water", Description = "Beyond the skies of the Plane of Air, the clouds grow darker and condense into the vast, spherical, liquid shell of the Plane of Water. Its nearly limitless stretches of saline, fresh, and brackish seas teem with all manner of oceanic life, lit by light from the border with the Plane of Air and descending into black, benthic depths where it borders the Plane of Earth. While the plane is perfectly amenable to water-breathing creatures, air-breathing travelers must provide their own supply of air or magical means to breathe. Bubbles of breathable atmosphere are relatively rare and securely guarded, anchored over places of trade and commerce with outsiders, such as the great city of Vialesk, founded by immigrant undines. The plane’s oceans, dotted by vast forests of kelp, magical currents, and strange phenomena, play host to empires of merfolk, predatory and expansionist sea devils, and the holdings of the plane’s great brine dragons. While marids once claimed nearly absolute dominion over the plane of their origin, their empire long ago fell into deterioration and disunity.Their ravaged cities sank into the depths, and their present - day holdings remain a shadow of their former grandeur.Kelizandri the Brackish Emperor, the evil elemental lord of water and cause of their ruin, rules the dark, saline depths, feasting on all rivals and hoarding the vast, stolen wealth of the fallen marid cities.Unlike other subjective gravity planes, on the Plane of Water, a creature moves based on its swim Speed and must use actions to Swim if it doesn’t have one." };
            yield return new Plane { Id = Guid.Parse("b31acddd-b42e-4014-95cf-0e9ca41c73d3"), CategoryId = Guid.Parse("3bbe8661-ea39-4b26-8723-eb04b151062f"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Positive Energy Plane", Description = "Known as Creation’s Forge, the Positive Energy Plane is at once the source of life-sustaining positive energy, the origin of all pre-incarnate mortal souls, and paradoxically the most innately hostile of all of the planes. While positive energy is deadly to undead and beneficial to living beings, such is the intensity of the plane that unmitigated exposure ultimately incinerates any extraplanar beings without sufficient magical protection. The most apt comparison for the plane’s interior is that of the heart of a burning star, and indeed the stars of the Material Plane each house natural portals to the Positive Energy Plane within their glowing, potent cores to foster the movement of pre-incarnate souls in their first steps in the great cycle of life and death.Brilliant and blinding, the plane’s interior is sparsely populated, and the resident phoenix - kin jyoti are intensely xenophobic.Dwelling in glimmering, radiant crystalline cities such as Arudrellisiir, they view themselves as gardeners and guardians of souls spawned from their realm’s burning quintessence.Intensely distrustful of gods and their servitors, jyoti can nonetheless be bargained with, and they have frequently taken into their custodianship any number of artifacts and imprisoned beings considered too dangerous to house on any other plane." };

            //Outer Sphere Planes
            yield return new Plane { Id = Guid.Parse("429fa72a-4a20-40ce-97b1-b4008807472b"), CategoryId = Guid.Parse("c64c6e93-aa40-4010-8fbc-592c1f0e017a"), AlignmentId = Guid.Parse("3a4f993d-9f0c-4615-b18a-39feb5b25a11"), Name = "Abaddon", Description = "A perpetual eclipse looms above the bleak wastelands of Abaddon, shedding an eerie half-light over a landscape of toxic, disease-ridden swamps, volcanic wastes, fog-shrouded forests, and the glittering, memory-devouring ribbon of the River Styx. An unnatural silence blankets the plane, cut only by the wails of petitioners falling from the sky like screaming, falling stars, or those already condemned upon the ground, desperate to find safety that doesn't exist. Daemons, the physical embodiments of death and oblivion, roam unchecked, owing allegiance only to the Four Horsemen of the Apocalypse: Death, Famine, Pestilence, and War. In the courts of the Horsemen and the neutral grounds of trade cities such as Awaiting-Consumption, the soul trade serves daemonic hunger and industrialized oblivion. Night hags and other creatures ply the trade or make their way along the margins of daemonic society, eager to avoid consumption themselves by the plane's nihilistic masters. Urgathoa and Zyphus claim divine domains here, their petitioners granted freedom from predation. Yet something far worse glares down upon these gods and the Horseman alike. Abaddon's perpetual eclipse may be nothing less than the lidded, comatose eye of the Bound Prince, the First Horseman, betrayed and cast down by the Four, forgotten by the cosmos at large, but far too powerful for them to destroy—waiting, watching, and hungering." };
            yield return new Plane { Id = Guid.Parse("10be56f4-5519-4cb6-8038-83dda6b0d00a"), CategoryId = Guid.Parse("c64c6e93-aa40-4010-8fbc-592c1f0e017a"), AlignmentId = Guid.Parse("25f9299a-9a7c-40bc-b8bd-58588d19381b"), Name = "Abyss", Description = "Like a corrosive rot in the roots of the Outer Sphere, or an antithetical, rival reality run aground into the Maelstrom at the dawn of time, the Abyss is a place of horror and destruction fed by mortal sin. Each of its innumerable regions is a unique iteration of chaos and evil, each with its own terrible and twisted environment, with one driving maxim: the strong survive, while the weak suffer and are destroyed. Ruled by demons, and before them by the alien, nightmarish qlippoth, the Abyss and its native beings seek only to ravage and destroy. While demons routinely rampage out into other planes when the Abyss manifests a great planar rift, the denizens of the Abyss are fractured and self-destructive. Demon lords such as Dagon, Pazuzu, and Zura, and even gods including the ascended demon lord Lamashtu, the Mother of Monsters, fight for dominion over the Abyss as much or more than they threaten the other planes. Though dangerous, not every realm of the Abyss is immediately hostile to the prepared traveler. Shamira’s city of Alushinyrra in the Midnight Isles and Abraxas’s library-city of Diovengia in the realm of Pleroma are each welcoming in their own dark ways. Even those who survive a journey through the Abyss, however, inevitably must resist being deeply corrupted by the experience." };
            yield return new Plane { Id = Guid.Parse("e57522d4-5e50-44c7-bbcb-1c4d0d81baeb"), CategoryId = Guid.Parse("c64c6e93-aa40-4010-8fbc-592c1f0e017a"), AlignmentId = Guid.Parse("617c34ca-c11b-4c02-9f97-5ce7269f98bc"), Name = "Axis", Description = "Axis is a realm of pure, absolute law, unhindered by the moral concerns of good or evil. The plane takes the form of a vast, gleaming, perfectly structured city. Built at the base of Pharasma’s Spire, the Perfect City is a bulwark against the chaos of the Maelstrom and Abyss, with vast mechanical armies of inevitables marching forth to explore, define, and pacify an imperfect, unruly universe. Axis is also home to axiomites: beings composed of living mathematics and equations who helped create the first inevitables. Axiomites continue to work on the maintenance of the inevitables, but increasingly turn their attentions to the planar city of Axis itself; as with any city, Axis requires non-stop maintenance and improvement in order to resist the march of time. Axis’s natives are far from the only inhabitants of their cosmopolitan realm.Devils and archons often visit along with petitioners, mortal travelers, and smaller numbers of most every other kind of extraplanar being.Abadar and other lawful deities make their homes here.The empty, former domain of Aroden languishes here, while below the streets lies Norgorber’s domain, a labyrinthine undercity." };
            yield return new Plane { Id = Guid.Parse("7c34baea-48a6-4a49-8b15-8781a5c1ab47"), CategoryId = Guid.Parse("c64c6e93-aa40-4010-8fbc-592c1f0e017a"), AlignmentId = Guid.Parse("094aecb0-6e14-433f-afa5-eb7d0f3ab64a"), Name = "Boneyard", Description = "The Boneyard spans an impossibly tall and ever-growing spire of gleaming quintessence that rises up into the silver void of the Astral Plane. As the destination of the River of Souls, the Boneyard is where the souls of the mortal dead arrive for judgment and for Pharasma and her psychopomp servitors to direct them to their respective afterlives. Pharasma’s domain is separated into eight courts, each corresponding to one of the other planes of the Outer Sphere and collecting the souls due to that plane. Not every soul goes unchallenged, and proxies of gods and planes argue and debate over souls, with final arbitration conducted by Pharasma herself. While Pharasma rules absolutely within the Boneyard, she is not the only divinity there.The demigod psychopomp ushers dwell within the plane in service to her, and the deity Achaekek dwells below at the spire’s root.Looming high above as a skull - faced moon waits Groetus, the god of the end times, his orbit slowly decaying in minuscule iterations supposedly counting down to the last days of the cosmos. Pharasma’s courts and the surrounding Graveyard of Souls are not the only features atop the spire.Beyond the graveyard, the Spirelands manifest environments much like those of the varied Material Plane worlds, filled with the souls of neutral petitioners who have nowhere else to go as they are unclaimed by any gods and unaligned with any particular ethos." };
            yield return new Plane { Id = Guid.Parse("cc26757e-a07a-4213-84a3-36b300a2306a"), CategoryId = Guid.Parse("c64c6e93-aa40-4010-8fbc-592c1f0e017a"), AlignmentId = Guid.Parse("add12009-9c8a-4287-b02b-7e5b9459bf44"), Name = "Elysium", Description = "Verdant, wild, and unrestrained by law, where passion and creation are fostered and rewarded, the plane of Elysium is a place of wild, idealized natural beauty. The so-called Promised Land and its inhabitants represent a wide variety of freely given benevolence, often willing to directly aid visitors but more often serving as inspirations and muses to foster positive change and self-realized success. Elysium’s petitioners, known as the chosen, appear as idealized versions of their mortal selves, each pursuing their own self-determined actions and finding their own unique paths to join the ranks of the plane’s celestials. Azatas—the plane’s primary denizens—organize into fleeting, competitive courts, each rewarding heroism and creativity above all else.Elysium hosts a number of resident deities, including Calistria and the elven pantheon, Cayden Cailean, Desna, Gorum, and various empyreal lords.Visitors from across the planes are drawn to Elysium’s Wandering City of Emerald Song, a mobile, impermanent, and ever-changing city of lillend azatas organized by their princess, Anduarine the Muse, filled with art, craft, revelry, song, and trade." };
            yield return new Plane { Id = Guid.Parse("84410831-a91b-4556-96a0-7eeba0653279"), CategoryId = Guid.Parse("c64c6e93-aa40-4010-8fbc-592c1f0e017a"), AlignmentId = Guid.Parse("2006ffe6-8a03-4d40-99ac-935d814140ec"), Name = "Heaven", Description = "The great mountain of Heaven is the realm of structured benevolence made manifest. Organized into seven tiers, the mountain’s solid appearance is actually malleable, making way for a vast assemblage of varied environments to accommodate both its own celestials and the souls who migrate there. Devoted to defending the innocent and crusading against the wicked, Heaven’s archons marshal into vast armies, commanded by their own empyreal lords. Angels collaborate with the archon legions but typically act in more direct service to Heaven’s resident deities, with Iomedae, Erastil, and Torag the most prominent among them. Petitioners known as the elect manifest at the mountain’s base, and their subsequent climb up the seemingly endless, unreachable heights is both a literal and figurative journey.Progress is about personal growth and spiritual purification as the petitioners grow more and more attuned to the plane.Likewise, progress from one layer to the next is often impossible without permission from the archons or spiritual alignment with Heaven itself.Most visitors arrive at the city of Heaven’s Shore, a place open to both traders and to pilgrims of good intent.Access beyond its heavily guarded walls is difficult, to say nothing of scaling the mountain.At its pinnacle is the Garden, Heaven’s ultimate layer.Unattended and empty, the Garden is a beautiful, transcendent mystery even to its resident deities, and the source of the plane’s call of self - perfection to its petitioners." };
            yield return new Plane { Id = Guid.Parse("cdd0a36f-c298-41e6-9252-d3cbc81f5bd6"), CategoryId = Guid.Parse("c64c6e93-aa40-4010-8fbc-592c1f0e017a"), AlignmentId = Guid.Parse("54f32060-3da3-4edf-b6dc-3839b8b7415d"), Name = "Hell", Description = "Hell is the realm of devils, the multiversal seat of tyranny and malignant law, and the divine domain of Asmodeus, the Prince of Darkness. Here every act is authorized, calculated, recorded, and set like perfectly ordered clockwork within a vast machine driven on methodical suffering and greased with pain and purification. The nine inverted layers of Hell violently oppose the surrounding fabric of the Maelstrom, each layer shaped to reflect the nature of its ruling archdevil. Avernus's volcanic wastes, ruled by Barbatos, are the marshaling place of Hell's armies, and where newly damned souls are shackled and shuffled off to their assigned torment. Dispater's layer of Dis is a great iron city: brutal, beautiful, and terrible. The layer of Erebus comprises both the sewers of Dis and the vaults and treasuries of Hell, ruled by Mammon, a great genius loci embodied by the very wealth locked within Hell's coffers. Ruled by Belial, the layer of Phlegethon hosts Hell's forges, while Geryon's watery realm of Stygia houses Hell's libraries. Moloch's smoldering, ash-draped forest realm of Malebolge is the training site of the infernal armies, and Baalzebul's frozen layer of Cocytus torments the imprisoned, starving damned. Mephistopheles rules the layer of Caina, a realm of cages and torture suspended above a pit of hungry darkness, while at the very bottom of Hell's infinite pit, Asmodeus rules unquestioned from his throne in Nessus." };
            yield return new Plane { Id = Guid.Parse("235e010f-bfb6-40f0-a65f-628f2ea721bf"), CategoryId = Guid.Parse("c64c6e93-aa40-4010-8fbc-592c1f0e017a"), AlignmentId = Guid.Parse("2ad80bbd-a735-4431-9e3a-f784e053b756"), Name = "Maelstrom", Description = "The Maelstrom, infinite and ancient, spawned the other Outer Planes in cosmological prehistory and surrounds them like a vast metaphorical—and at times literal—ocean of raw, chaotic quintessence. Where the Maelstrom borders these other planes, its structure takes on their characteristics, albeit in an unpredictable, chaotic fashion. Beyond these so-called Borderlands, however, the Maelstrom reverts to its true nature, the Cerulean Void: a trackless, liquid infinity devoid of stability and permanence where serpentine proteans create and destroy with profound frivolity. The proteans are paradoxically organized into discrete choruses, each with its own philosophy and goals in service to the Maelstrom. Swirling with oddities and wild magic, bereft of laws and structure, the Maelstrom also serves as a conduit between the other Outer Planes utilized by armies of extraplanar beings, hordes of demons spilling forth from the Abyss, and the innumerable protean choruses seeking to return the rest of the planes to the true freedom of the chaos from which they emerged. Sufficiently powerful magic can stabilize the chaos for a time, allowing for the creation of demiplanes and stable islands. The massive planar trade city of Galisemni is most prominent among these, drifting through the chaos." };
            yield return new Plane { Id = Guid.Parse("b1ed0a25-c679-4365-a45e-4d7fc057c1d9"), CategoryId = Guid.Parse("c64c6e93-aa40-4010-8fbc-592c1f0e017a"), AlignmentId = Guid.Parse("e45c48a5-db00-4056-8ef3-7bd3662cfd9f"), Name = "Nirvana", Description = "The pastoral paradise of Nirvana is the realm of purest good, a plane that promises sanctuary to the weary and enlightenment and transcendence to those who seek it out. Filled with beautiful wilderness of all types in perfect harmony with its occupants, Nirvana’s wilds are home to angels and others. The plane’s petitioners, known as the cleansed, most often take the forms of glorified, sapient wild animals, though many eventually leave their carefree existence to aid others, ascending to assist the benevolent works of angels. Devoted to guiding and assisting mortals, angels are often charged with delivering important messages that reflect the will of benevolent deities Various divinities make their home amid Nirvana’s wilds, including a host of empyreal lords and, most prominently, Sarenrae and Shelyn.While the great cities of High Ninshabur and Llourith welcome visitors most mortals visiting Nirvana witness the plane’s beauty and supernatural feeling of peace but rarely encounter many of its residents, as the plane itself protectively hides much of its contents from any but the most selfless and pure of heart.The plane’s hinterlands hint at hidden mysteries, including legends that the plane shelters the vanished heroes of innumerable mortal worlds, peacefully sleeping until their peoples’ times of greatest need." };
        }
    }

    public class PlaneTraitJoiner : IEntityJoiner<Plane, PlaneTrait>
    {
        public PlaneTrait[] Join(Plane plane, PlaneTrait[] traits)
        {
            return plane.Name switch
            {
                "Astral Plane" => Filter(traits, "Subjective Gravity", "Timeless"),
                "Ethereal Plane" => Filter(traits, "Subjective Gravity"),
                "First World" => Filter(traits, "Erratic Time", "Metamorphic"),
                "Shadow Plane" => Filter(traits, "Shadow"),

                "Dimension of Time" => Filter(traits, "Erratic Time", "Static"),
                "Dreamlands" => Filter(traits, "Flowing"),

                "Material Plane" => Array.Empty<PlaneTrait>(),
                "Negative Energy Plane" => Filter(traits, "Negative", "Unbounded", "Subjective Gravity"), 
                "Plane of Air" => Filter(traits, "Air", "Subjective Gravity"), 
                "Plane of Earth" => Filter(traits, "Earth"), 
                "Plane of Fire" => Filter(traits, "Fire"), 
                "Plane of Water" => Filter(traits, "Water", "Subjective Gravity"), 
                "Positive Energy Plane" => Filter(traits, "Positive", "Unbounded", "Subjective Gravity"),

                "Abaddon" => Array.Empty<PlaneTrait>(),
                "Abyss" => Array.Empty<PlaneTrait>(),
                "Axis" => Array.Empty<PlaneTrait>(),
                "Boneyard" => Filter(traits, "Timeless"),
                "Elysium" => Array.Empty<PlaneTrait>(),
                "Heaven" => Array.Empty<PlaneTrait>(),
                "Hell" => Array.Empty<PlaneTrait>(),
                "Maelstrom" => Filter(traits, "Metamorphic"),
                "Nirvana" => Array.Empty<PlaneTrait>(),
                _ => Array.Empty<PlaneTrait>()
            };
        }

        private static PlaneTrait[] Filter(PlaneTrait[] planeTraits, params string[] planeTraitNames)
        {
            PlaneTrait[] matches = planeTraits
                .Where(domain => planeTraitNames.Contains(domain.Name))
                .ToArray();

            return matches.Length == planeTraitNames.Length
                ? matches
                : throw new InvalidOperationException($"Not all plane traits names could be found: {string.Join(", ", matches.Select(e => e.Name).GetMissing(planeTraitNames))}.");
        }
    }
}
