using Silvester.Pathfinder.Official.Database.Models;
using System;
using System.Collections.Generic;

namespace Silvester.Pathfinder.Official.Database.Seeding.Seeds
{
    public class PlaneTraitSeeder : IEntitySeeder<PlaneTrait>
    {
        public IEnumerable<PlaneTrait> GetSeedEntities()
        {
            yield return new PlaneTrait { Id = Guid.Parse("44acf71b-a1e2-4cb4-9596-dace6c47d0f1"), Name = "Enhanced and Impeded Magic", Description = "Some planes enhance certain magic and impede opposing effects. A plane that enhances a particular type of magic grants anyone Casting a Spell with that trait a +1 circumstance bonus to their spell DC or spell attack roll with that spell. Impeded magic means a character who Casts a Spell or Activates an Item with the specified trait must succeed at a DC 6 flat check or lose the spell or activation." };
            yield return new PlaneTrait { Id = Guid.Parse("b04c60f8-feab-4d1f-964c-63674f871191"), Name = "Alignment", Description = "Certain planes, particularly in the Outer Sphere, are attuned to an alignment. Most inhabitants share that alignment— even powerful creatures such as deities. Planes with the neutral alignment trait are more often a mix of alignments than strongly neutral, and planes with no alignment affinity simply don’t have an alignment trait, rather than being neutral. Alignments are given as an abbreviation (Pathfinder Bestiary 345), which appears first in the plane’s list of traits. Spells that share any of the plane’s alignment traits are enhanced, and those with opposing traits are impeded.For instance, in the chaotic evil Abyss, chaotic and evil spells are enhanced, and lawful and good spells are impeded." };
            yield return new PlaneTrait { Id = Guid.Parse("2f525514-878f-4127-a702-b349b9bfb777"), Name = "Scope", Description = "Most planes are immeasurable, so immense they are impossible to quantify. Which immeasurable planes, if any, are infinite is a subject of debate among philosophers and scholars alike. Since so many planes are immeasurable, those planes omit a scope trait. Otherwise, the plane likely has either the finite or unbounded trait." };
            yield return new PlaneTrait { Id = Guid.Parse("48204675-e1dd-4ec1-89d6-7fee012a50d5"), Name = "Normal Gravity", Description = "Bodies of great mass are the centers of gravity, and objects fall toward those centers with a measured amount of force relative to the size of the body." };
            yield return new PlaneTrait { Id = Guid.Parse("75c056af-e3c7-4c22-866a-f27533399b6b"), Name = "High Gravity", Description = " As in normal gravity, bodies of great mass act as centers of gravity, but the force relative to the size of the body is greater than on the Material Plane. The Bulk of all creatures and objects is doubled, meaning creatures acclimated to normal gravity can carry only half as much. Creatures used to normal gravity move at half Speed and can jump only half as high and far. Physical ranged attacks are impossible beyond the third range increment (instead of the sixth). Creatures that fall in high gravity take bludgeoning damage equal to the distance they fell." };
            yield return new PlaneTrait { Id = Guid.Parse("9cb4a5c0-d672-47f3-9d21-6b91c5714d5b"), Name = "Low Gravity", Description = "As in normal gravity, bodies of great mass act as centers of gravity, but the force relative to the size of the body is less than on the Material Plane. The Bulk of all creatures and objects is halved, meaning creatures acclimated to normal gravity can carry twice as much and jump twice as high and far. Physical ranged attacks are possible up to the twelfth range increment (instead of the sixth). Creatures that fall in low gravity take no damage for the first 10 feet of a fall, and then take bludgeoning damage equal to a quarter of the remaining distance it fell." };
            yield return new PlaneTrait { Id = Guid.Parse("f3d65fdd-a015-4432-a2bd-5f85b00159a3"), Name = "Microgravity", Description = "There is little to no gravity on this plane. Creatures float in space unless they can push off a surface or use some force to propel themselves throughout the plane." };
            yield return new PlaneTrait { Id = Guid.Parse("fe17801c-43b7-4bbc-802d-40e2bc8b4b5b"), Name = "Strange Gravity", Description = "All bodies of mass are centers of gravity with roughly the same force. A creature can stand on any solid objects that is as large as or larger than themself." };
            yield return new PlaneTrait { Id = Guid.Parse("5f8d1fc6-5199-4c64-9633-f22db88b0b9e"), Name = "Subjective Gravity", Description = "All bodies of mass can be centers of gravity with the same force, but only if a non-mindless creature wills it. Unattended items, objects, and mindless creatures treat the plane as having microgravity. Creatures on a plane with subjective gravity can move normally along a solid surface by imagining “down” near their feet. Designating this downward direction is a free action that has the concentration trait. If suspended in midair, a creature can replicate flight by choosing a “down” direction and falling in that direction, moving up to their Speed or fly Speed. This pseudo-flight uses the Fly action." };
            yield return new PlaneTrait { Id = Guid.Parse("5dca1675-95f7-4411-b1c3-307e98aaf2c7"), Name = "Normal Time", Description = " Time passes the same way it does on the Material Plane. One hour on a plane with normal time equals 1 hour on the Material Plane." };
            yield return new PlaneTrait { Id = Guid.Parse("2556952c-915d-4bc6-85f2-39b640854c9b"), Name = "Erratic Time", Description = "Time slows down and speeds up, so an individual may lose or gain time as they move between planes. When a creature moves from a plane with erratic time to one with normal time, roll a DC 11 flat check. Creatures that leave an erratic time plane together share the same result." };
            yield return new PlaneTrait { Id = Guid.Parse("ccc03793-3fbe-4947-b411-96b49613e5c6"), Name = "Flowing", Description = "Planes with this trait have a flow of time that is consistently faster or slower than that of other planes" };
            yield return new PlaneTrait { Id = Guid.Parse("eba4f250-66db-48f2-b902-1398ba91a753"), Name = "Timeless", Description = "Time still passes, but the effects of time are diminished. Creatures on these planes don’t feel hunger, thirst, or the effects of aging or natural healing. The effects of poison, diseases, and other kinds of healing may also be diminished on certain timeless planes. Spell energy and other effects still dissipate, so the durations of spells and other effects function as normal. The danger of this trait is that when a creature leaves a timeless plane and enters a plane with another time trait, the effects of hunger, thirst, aging, and other effects slowed or arrested by the timeless trait occur retroactively in the instant of transition, possibly causing the creature to immediately starve or die of old age." };
            yield return new PlaneTrait { Id = Guid.Parse("8112fec1-79be-4738-9dc1-d98222fc1a6f"), Name = "Metamorphic", Description = "Objects remain where they are (and what they are) unless affected by physical force or magic. Creatures can change the immediate environment as a result of tangible effort, such as by digging a hole." };
            yield return new PlaneTrait { Id = Guid.Parse("9c610160-b8ea-4d22-833b-f3dd8bf068c1"), Name = "Sentient", Description = "The plane changes based on its own whims." };
            yield return new PlaneTrait { Id = Guid.Parse("c5358cea-44ea-4ef0-b6eb-281bdbc80e2a"), Name = "Static", Description = "Visitors can’t affect living residents of the plane or objects the denizens carry in any way. Any spells that would affect those on the plane have no effect unless the static trait is somehow removed or suppressed." };
            yield return new PlaneTrait { Id = Guid.Parse("76206317-bdb6-4f71-b4c6-6536d06172d9"), Name = "Air", Description = "Planes with this trait consist mostly of open spaces and air of various levels of turbulence, though they also contain rare islands of floating stone and other elements and energies. Air planes usually have breathable atmospheres, though they may include clouds of acidic or toxic gas. Air magic is enhanced, and earth magic is impeded. Earth creatures often find themselves at a disadvantage within air planes, which tend to at least make them uncomfortable, as there is little solid ground for them to gain their bearings." };
            yield return new PlaneTrait { Id = Guid.Parse("9740e5d6-b49e-4827-8962-e70ffaa4e8be"), Name = "Earth", Description = "These planes are mostly solid. Travelers arriving upon an earth plane risk suffocation if they don’t reach a cavern or some other air pocket within the plane’s solid matter. Creatures who can’t burrow are entombed in the plane’s substance and must attempt to dig their way toward an air pocket. Earth magic is enhanced, and air magic is impeded. Air creatures are ill at ease, as they rarely have the space to move freely through even the most lofty warrens." };
            yield return new PlaneTrait { Id = Guid.Parse("a415e74d-e174-4573-b311-c02ea2fc2875"), Name = "Fire", Description = "Planes with this trait are composed of flames that continually burn with no fuel source. Fire planes are extremely hostile to non-fire creatures. Unprotected wood, paper,cloth, and other flammable materials catch fire almost immediately, and creatures wearing unprotected flammable clothing catch fire, typically taking 1d6 persistent fire damage.Extraplanar creatures take moderate environmental fire damage at the end of each round(sometimes minor environmental damage in safer areas, or major or massive damage in even more fiery areas).Fire magic is enhanced, and cold and water magic are impeded.Water creatures are extremely uncomfortable on a fire plane, and any natural resistance they have against fire doesn’t function against this environmental fire damage." };
            yield return new PlaneTrait { Id = Guid.Parse("83998080-dd80-4522-b1ef-75c6918c35ff"), Name = "Water", Description = "These planes are mostly liquid. Visitors who can’t breathe water or reach an air pocket likely drown. Water magic is enhanced, and fire magic is impeded. Creatures with a weakness to water take damage equal to double their weakness at the end of each round." };
            yield return new PlaneTrait { Id = Guid.Parse("e7f12fc2-3003-4472-9ff0-904a838e1e75"), Name = "Negative", Description = "Planes with this trait are vast, empty reaches that suck the life from the living. They tend to be lonely, haunted planes, drained of color and filled with winds carrying the moans of those who died within them. At the end of each round, a living creature takes at least minor negative environmental damage. In the strongest areas of a negative plane, they could take moderate or even major negative damage at the end of each round. This damage has the death trait, and if a living creature is reduced to 0 Hit Points by this negative damage and killed, it crumbles into ash and can become a wraith (Bestiary 335). Negative magic is enhanced, and positive magic is impeded." };
            yield return new PlaneTrait { Id = Guid.Parse("348aeff9-7683-4763-b61d-79cba5b4547d"), Name = "Positive", Description = "These planes are awash with life energy. Colors are brighter, fires are hotter, noises are louder, and sensations are more intense. At the end of each round, an undead creature takes at least minor positive environmental damage. In the strongest areas of a positive plane, they could take moderate or even major positive damage at the end of each round. While this might seem safe for living creatures, positive planes present a different danger. Living creatures regain an amount of HP each round equal to the environmental damage undead take in the same area. If this would bring the living creature above their maximum HP, any excess becomes temporary HP. Unlike normal, these temporary HP combine with each other, and they last until the creature leaves the plane. If a creature’s temporary HP from a positive plane ever exceeds its maximum HP, it explodes in a burst of overloaded positive energy, spreading across the area to birth new souls. Positive magic is enhanced, and negative magic is impeded." };
            yield return new PlaneTrait { Id = Guid.Parse("97dd8e80-f871-4a0b-943c-c6fc6b532d81"), Name = "Shadow", Description = "Planes with this trait are umbral with murky light. On a shadow plane, the radius of all light from light sources and the areas of light spells are halved. Darkness and shadow magic are enhanced, and light magic is impeded." };
            yield return new PlaneTrait { Id = Guid.Parse("7b459163-b6bf-4471-976f-3489eab76349"), Name = "Unbounded", Description = "Planes with this trait loop back on themselves when a creature reaches the plane’s edge." };
        }
    }
}
