using Silvester.Pathfinder.Reference.Database.Models.Entities;
using Silvester.Pathfinder.Reference.Database.Models.Prerequisites.Builders;
using Silvester.Pathfinder.Reference.Database.Models.Prerequisites.Instances;
using Silvester.Pathfinder.Reference.Database.Utilities.Text;
using System;
using System.Collections.Generic;

namespace Silvester.Pathfinder.Reference.Database.Seeding.Seeds.Feats.Instances
{
    public class SecretsOfShadow : Template
    {
        public static readonly Guid ID = Guid.Parse("a7e0528d-5e24-4b8c-be2f-c55ca02d0547");

        protected override Feat GetFeat()
        {
            return new Feat
            {
                Id = ID,
                Name = "Secrets of Shadow",
                Level = 12,
                ActionTypeId = ActionTypes.Instances.NoAction.ID,
                CanBeLearnedMoreThanOnce = false,
                Special = null,
                Trigger = null,
                Frequency = null
            };
        }

        protected override IEnumerable<TextBlock> GetDetailBlocks()
        {
            yield return new TextBlock { Id = Guid.Parse("eab69e11-667d-422b-9094-119f7799cafc"), Type = TextBlockType.Text, Text = "Your shadow’s voice grows ever clearer; it whispers secrets of true power to you and shields your flesh from harm. Your shadow reservoir gains an additional spell 1 level below the highest level spell you can cast, in addition to the spells it already contains for all the levels below that." };
            yield return new TextBlock { Id = Guid.Parse("e1106806-37d1-411f-92d3-42212480ccf5"), Type = TextBlockType.Text, Text = "In addition, the tattoos generated by casting shadow spells protect your body against harmful energies. You gain negative resistance equal to the highest level of spell you can cast from spell slots; if you have negative healing (or are otherwise harmed by positive damage and not negative damage), you instead gain positive resistance in the same amount." };
        }

        protected override void GetPrerequisites(BooleanPrerequisiteBuilder builder)
        { 
            
            builder.HaveSpecificFeat(Guid.Parse("d92cf64f-e294-459d-8e8e-f39caa581cf5"), Feats.Instances.ShadowReservoir.ID);
        }

        protected override IEnumerable<Guid> GetTraits()
        {
            yield break;   
        }            

        protected override SourcePage GetSourcePage()
        {
            return new SourcePage
            {
                Id = Guid.Parse("35a5ee5d-4257-49df-a57c-6ad06f90ab47"),
                SourceId = Sources.Instances.SecretsOfMagic.ID,
                Page = -1
            };
        }
    }
}
